### ISSUE TITLE
Promptgen 1.5 support

### ISSUE THREAD

**Issue by shivshankar11** [FennelFetish/qapyq#4]
please add Promptgen 1.5 support

**Comment by FennelFetish** [comment]
I added a [Florence-2](https://huggingface.co/collections/microsoft/florence-6669f44df0d87d9c3bfb76de) backend that also works with [Florence-2-large-PromptGen-v1.5](https://huggingface.co/MiaoshouAI/Florence-2-large-PromptGen-v1.5).

It doesn't support system prompts, custom prompts or conversations. But you can still give it multiple tasks by writing the prompt like this:

```
<DETAILED_CAPTION>
---
<CAPTION_TO_PHRASE_GROUNDING> Raising moon behind building.
---
<OCR>
```

For these models, it might be better to set temperature to 0.0 to disable sampling.
